version: '3.8'

services:
  # Node.js application service
  node-app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Use the MongoDB service name defined below as the host
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
  
  # MongoDB database service
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
